# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc519af25ab0ab258844fdc43a0d3fe648d3e6d03a200543d25e6344a9162a7832e9b1ab4f01b2075e8e22b895f38ba33deef732328fbea26a1738dba6fc41bb

test:
  secret_key_base: 346d60f38b2cb68d11487bfbc8cbc1afad8db110baae02d3b3291621d6f7ae1a515feb36fc7741faa5c553700ce50735be7ffa2105abc20446ea3a046cdbd87c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
